version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - mysql
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - MYSQL_URI=mysql://root:25251525@mysql:3306/ecommerce
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "25251525"
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./data/mysql:/var/lib/mysql